version: '3.8'
services:
  api:
    build:
      context: ./Vnmonitoring.Server
    ports:
      - "5000:80"
    depends_on:
      - postgres

  client:
    build:
      context: ./vnmonitoring.client
    ports:
      - "3000:80"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: data_weather
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
