version: '3.8'
services:
  api:
    build:
      context: ./Vnmonitoring.Server
    ports:
      - "7101:80"

  client:
    build:
      context: ./vnmonitoring.client
      args:
        IS_DOCKER: "true"
    environment:
      - IS_DOCKER=true
    ports:
      - "3000:80"
    depends_on:
      - api
      
      
volumes:
  pgdata: