version: '3.8'
services:
  api:
    build:
      context: ./Vnmonitoring.Server
    ports:
      - "7101:80"

  client:
    build:
      context: ./vnmonitoring.client
      args:
        IS_DOCKER: "true"
    environment:
      - IS_DOCKER=true
    ports:
      - "3000:80"
    depends_on:
      - api
      
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_DB: data_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - client

      
volumes:
  pgdata: