version: '3.8'
services:
  api:
    build:
      context: ./Vnmonitoring.Server
    ports:
      - "5000:80"

  client:
    build:
      context: ./vnmonitoring.client
      args:
        IS_DOCKER: "true"
    environment:
      - IS_DOCKER=true

volumes:
  pgdata: